#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb 13 20:41:25 2021

@author: juliehembeck
"""
#function that sums between any two values



def sumbetweennumbers(initial_value, final_value):
    for x in range(initial_value + 1, final_value + 1):
        initial_value += x
        
    return initial_value

print(sumbetweennumbers(48 , 50))



